with dates as (
    {{ dbt_date.get_date_dimension('2015-01-01', '2026-01-01') }}
)
select
    cast(date_day as datetime) as date_day,
    cast(prior_date_day as datetime) as prior_date_day,
    cast(next_date_day as datetime) as next_date_day,
    cast(prior_year_date_day as datetime) as prior_year_date_day,
    cast(prior_year_over_year_date_day as datetime) as prior_year_over_year_date_day,
    cast(week_start_date as datetime) as week_start_date,
    cast(week_end_date as datetime) as week_end_date,
    cast(prior_year_week_start_date as datetime) as prior_year_week_start_date,
    cast(prior_year_week_end_date as datetime) as prior_year_week_end_date,
    cast(iso_week_start_date as datetime) as iso_week_start_date,
    cast(iso_week_end_date as datetime) as iso_week_end_date,
    cast(prior_year_iso_week_start_date as datetime) as prior_year_iso_week_start_date,
    cast(prior_year_iso_week_end_date as datetime) as prior_year_iso_week_end_date,
    cast(month_start_date as datetime) as month_start_date,
    cast(month_end_date as datetime) as month_end_date,
    cast(prior_year_month_start_date as datetime) as prior_year_month_start_date,
    cast(prior_year_month_end_date as datetime) as prior_year_month_end_date,
    cast(quarter_start_date as datetime) as quarter_start_date,
    cast(quarter_end_date as datetime) as quarter_end_date,
    cast(year_start_date as datetime) as year_start_date,
    cast(year_end_date as datetime) as year_end_date,
    day_of_week,
    day_of_week_iso,
    day_of_week_name,
    day_of_week_name_short,
    day_of_month,
    day_of_year,
    week_of_year,
    iso_week_of_year,
    prior_year_week_of_year,
    prior_year_iso_week_of_year,
    month_of_year,
    month_name,
    month_name_short,
    quarter_of_year,
    year_number
from dates